<a href="https://colab.research.google.com/github/jbcvasconcelos/aula3/blob/main/atividade21_05_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd
import numpy as np

In [2]:
df_gapminder = px.data.gapminder()
display(df_gapminder.head())

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4

In [3]:
df_2007 = df_gapminder[df_gapminder['year'] == 2007]


fig = px.scatter(
    df_2007,
    x='gdpPercap',
    y='lifeExp',
    title="Expectativa de Vida vs PIB per capita(2007)"

)

fig.show()

In [4]:
fig = px.scatter(
    df_2007,
    x='gdpPercap',
    y='lifeExp',
    color="continent",
    size="pop",
    hover_name="country",
    log_x=True,
    size_max=60,
    title="Expectativa de Vida vs PIB per capita(2007) - Melhorado"

)

fig.show()

In [5]:
df_brasil = df_gapminder[df_gapminder['country'] == 'Brazil']

fig = px.line(
    df_brasil,
    x='year',
    y='lifeExp',
    title="Expectativa de vida no Brasil 1952-2007",
    markers=True
)

fig.show()

In [6]:
paises_sulamericanos = [' Brazil', 'Argentina', 'Chile', 'Colombia', 'Peru']
df_sul = df_gapminder[df_gapminder['country'].isin(paises_sulamericanos)]


fig = px.line(
    df_sul,
    x='year',
    y='lifeExp',
    color='country',
    title="Evoluçao Da Expectativa de Vida na América Do Sul",
    markers=True
)

fig.show()

In [7]:
df_americas_2007 = df_2007[df_2007['continent']=='Americas'].sort_values('pop', ascending=False)

fig = px.bar(
    df_americas_2007,
    x ="country",
    y ="pop",
    title=" Popualaçao dos países das américas (2007)",
    color="lifeExp",
    color_continuous_scale=px.colors.sequential.Viridis,

)

fig.show()

In [8]:
df_tips = px.data.tips()
display (df_tips.head())

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [9]:
fig = px.histogram(
    df_tips,
    x='total_bill',
    title="Distribuição do Valor Total da Conta",
    nbins= 30,
    marginal="box",
    color_discrete_sequence=['indianred']
)

fig.show()

In [10]:
fig = px.box(
    df_tips,
    x="day",
    y="total_bill",
    color="smoker",
    title="Valor Total da Conta por Dia da Semana",
    points="all",
    category_orders={"day": ["Thur", "Fri", "Sat", "Sun"]}
)

fig.show()

In [11]:
fig = px.violin(
    df_tips,
    x="day",
    y="total_bill",
    color="sex",
    box=True,
    points="all",
    title="Gráfico Violin da Conta por Dia da Semana",
    category_orders={"day": ["Thur", "Fri", "Sat", "Sun"]}
)

fig.show()

In [12]:
pop_continente = df_2007.groupby('continent')['pop'].sum().reset_index()


fig = px.pie(
    pop_continente,
    values='pop',
    names='continent',
    title='distribuiçao da populaçao Mundial  por Continente',
    hole=0.0
)

fig.update_traces(textposition='inside', textinfo='percent+label')

fig.show()

In [13]:
fig = px.treemap(
    df_2007,
    path=[px.Constant('Mundo'), 'continent', 'country'],
    values='pop',
    color='lifeExp',
    color_continuous_scale='RdBu',
    title='Treemap: Expectativa de Vida '
)
fig.update_layout(margin=dict(t=50, l=25, r=25, b=25))
fig.show()